package simpledb;
import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends AbstractDbIterator {
	private final JoinPredicate joinPredicate;
	private final DbIterator dbIterator1;
	private final DbIterator dbIterator2;
	private final TupleDesc tupleDesc;
	private Tuple tuple1;
	private Tuple tuple2;

    /**
     * Constructor.  Accepts to children to join and the predicate
     * to join them on
     *
     * @param p The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
    	this.joinPredicate = p;
    	this.dbIterator1 = child1;
    	this.dbIterator2 = child2;
    	this.tupleDesc = TupleDesc.combine(child1.getTupleDesc(), child2.getTupleDesc());
    }

    /**
     * @see simpledb.TupleDesc#combine(TupleDesc, TupleDesc) for possible implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return tupleDesc;
    }

    public void open()
        throws DbException, NoSuchElementException, TransactionAbortedException {
    	dbIterator1.open();
    	dbIterator2.open();
    	if (dbIterator1.hasNext()) tuple1 = dbIterator1.next();
    	if (dbIterator2.hasNext()) tuple2 = dbIterator2.next();
    }

    public void close() {
    	super.close();
    	dbIterator1.close();
    	dbIterator2.close();
    	tuple1 = null;
    	tuple2 = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
    	dbIterator1.rewind();
    	dbIterator2.rewind();
    	if (dbIterator1.hasNext()) tuple1 = dbIterator1.next();
    	if (dbIterator2.hasNext()) tuple2 = dbIterator2.next();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no more tuples.
     * Logically, this is the next tuple in r1 cross r2 that satisfies the join
     * predicate.  There are many possible implementations; the simplest is a
     * nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of
     * Join are simply the concatenation of joining tuples from the left and
     * right relation. Therefore, if an equality predicate is used 
     * there will be two copies of the join attribute
     * in the results.  (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple readNext() throws TransactionAbortedException, DbException {
    	if (tuple1 == null || tuple2 == null) return null;
    	Tuple tuple = null;
    	while (tuple == null && tuple1 != null && tuple2 != null) {
    		if (joinPredicate.filter(tuple1, tuple2)) {
    			tuple = new Tuple(tupleDesc);
    		    int tuple1NumFileds = tuple1.getTupleDesc().numFields();
    		    int tuple2NumFields = tuple2.getTupleDesc().numFields();
    		    for (int i = 0; i < tuple1NumFileds; i++) {
    		    	tuple.setField(i, tuple1.getField(i));
    		    }
    		    for (int i = 0; i < tuple2NumFields; i++) {
    		    	tuple.setField(tuple1NumFileds + i, tuple2.getField(i));
    		    }
    		}
    		if (!dbIterator1.hasNext() && !dbIterator2.hasNext()) {
    			tuple1 = null;
    			tuple2 = null;
    		} else {
    			if (!dbIterator2.hasNext()) {
    				tuple1 = dbIterator1.next();
    				dbIterator2.rewind();
    			}
    			tuple2 = dbIterator2.next();
    		}
    	}
    	return tuple;
    }
}
